### ISSUE TITLE
Echo actions back to user

### ISSUE THREAD

**Issue by sklirg** [dotkom/super-duper-fiesta#189]
This is mainly for the user voting action, but might be relevant for other actions as well.

If a user votes on an issue on two devices simultaneously it looks like both votes are accepted. The back end will not allow this, but both devices shows votes for different alternatives which is not intuitive in showing what is actually voted for.

**Comment by duvholt** [comment]
Fixed by #203

**Comment by sklirg** [comment]
Did #203 really implement echoing back the vote to the user so that it renders the correctly voted option in the view?

**Comment by duvholt** [comment]
Oops. No, looks like I misread. It does provide feedback when trying to double vote though.
