### ISSUE TITLE
Displayed recently concluded issue outside of the concluded issue list 

### ISSUE THREAD

**Issue by duvholt** [dotkom/super-duper-fiesta#235]
When an issue is closed it is moved to the list of concluded issues. If the user has not opened this list it just looks like the issue disappears.

One possible solution is to always show the latest concluded issue above the list.

**Comment by sklirg** [comment]
I'm having an idea that might solve this with regards to #137.

I'll keep this in mind for that one and maybe I'll kill two birds with one stone.
