### ISSUE TITLE
Service Worker for push notifications

### ISSUE THREAD

**Issue by duvholt** [dotkom/super-duper-fiesta#264]
Our implementation of notification only works on desktop. 

Since we also support mobile phones we should add support for service worker push notifications. 
Probably not a bad idea to use service worker anyway. 

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

**Comment by sklirg** [comment]
https://sentry.io/dotkom/genfors/issues/396573466/

**Comment by sklirg** [comment]
Resolved in #281.
