### ISSUE TITLE
Admin buttons doesn't render text in safari

### ISSUE THREAD

**Issue by martinlunde** [dotkom/super-duper-fiesta#303]
<img width="1090" alt="skjermbilde 2018-02-14 kl 20 15 08" src="https://user-images.githubusercontent.com/14068159/36223275-2c2d93da-11c4-11e8-9dc8-bc4f8e4c14f6.png">

**Comment by Letaguator** [comment]
It works for me (Safari 11.0.3)
<img width="718" alt="screenshot_safari" src="https://user-images.githubusercontent.com/31246008/36809226-9e95a6a2-1cc7-11e8-88eb-27ea19070718.png">
