### ISSUE TITLE
Don't force to load assets from root (/)

### ISSUE THREAD

**Issue by sklirg** [dotKom/super-duper-fiesta#6]
With d85ddfe19b5799e88803ecd24a047372f75e8669 we started loading assets directly from root (`/`). This makes it very hard to use reverse proxies, and we should replace the current solution with something more generic.

I know axios has support for this, but we might not want all of the other stuff that comes with it.

**Comment by torjusti** [comment]
Is it better to inject a path using WebPack? We can use HtmlWebpackPlugin, then just update the publicPath if we need to.

**Comment by duvholt** [comment]
Yep, that's definitely the way to go. 
In the future we likely want to create filenames with hashes in them for better caching and therefore cannot rely on a hardcoded name at all.
