### ISSUE TITLE
Find a way to use same data structures for frontend and backend

### ISSUE THREAD

**Issue by sklirg** [dotkom/super-duper-fiesta#66]
React (redux) does a nice job with actionTypes. However, they are exported in a way Node doesn't understand, so importing the constants from there does not work. Therefore, the backend is written using hard coded values as its actions.

We should find a way to unify these values for the frontend and backend so that we can set the value one place and use it throughout the project by simply importing its type.

**Comment by duvholt** [comment]
I think our options is to either use CommonJS syntax (module.exports) or transpile with Babel. 
Babel converts ES6 modules to CommonJS.

Adding a build step to the NodeJS backend just for ES6 style modules (without getting any of the ES6 module benefits) seems like overkill to me. Using something like this seems cleaner:

```javascript
module.exports = {
  AUTH_SIGNED_IN: 'AUTH_SIGNED_IN',
  AUTH_SIGN_OUT: 'server/AUTH_SIGN_OUT',
  AUTH_SIGNED_OUT: 'AUTH_SIGNED_OUT',
  AUTH_REGISTER: 'server/AUTH_REGISTER',
  AUTH_REGISTERED: 'AUTH_REGISTERED',
};

```
